### ISSUE TITLE
非fine tune的时候lstm和crf层的参数为啥不学习？

### ISSUE THREAD

**Issue by gikerch** [hemingkx/CLUENER2020#11]
https://github.com/hemingkx/CLUENER2020/blob/4bfd0b5fdd1537558f0c32dd28339af1f337afc9/BERT-LSTM-CRF/run.py#L124

![image](https://user-images.githubusercontent.com/22066778/156990638-6f47397c-9c9c-4edd-9a35-bc9b2116f404.png)

**Comment by zjmwqx** [comment]
而且lstm也不学？

**Comment by zjmwqx** [comment]
我觉得这个非fine tune是不是没有测过啊

**Comment by pustar** [comment]
能不能提供一个BiLSTM-CRF的预训练模型啊？感谢！

**Comment by hemingkx** [comment]
非finetune的应该没用过 这里是有问题的 可以自己改一下 不难的~
