### ISSUE TITLE
dataloder加载出错

### ISSUE THREAD

**Issue by zhw666888** [hemingkx/CLUENER2020#2]

**Comment by hemingkx** [comment]
Could you paste your train log (including the error information) here?

**Comment by zhw666888** [comment]
你好，bert系列模型中的data_loader文件单独运行会，报错：
line 96, in collate_fn
&nbsp; &nbsp; batch_labels[j][:cur_tags_len] = labels[j]
ValueError: could not broadcast input array from shape (141,) into shape (140,)

我目前对此报错不得理解，因为同样的操作，但却有10来条数据缺确实会造成这样的错误，但是总体去运行似乎并没有见到这个报错。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hemingkx/CLUENER2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月7日(星期一) 晚上7:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hemingkx/CLUENER2020] dataloder加载出错 (#2)





 
Could you paste your train log (including the error information) here?

**Comment by hemingkx** [comment]
因为在整体运行时，dataloader之前需要有一步数据预处理，你参照run.py中的逻辑，每一步对比一下数据就知道了～。

**Comment by zhw666888** [comment]
您好，不知道换不同的数据集，bertconfig需要为不同数量标签做些参数的改变？因为报错标签这里总是会出错。



---原始邮件---
发件人: "Heming ***@***.***&gt;
发送时间: 2021年6月9日(周三) 上午9:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hemingkx/CLUENER2020] dataloder加载出错 (#2)




 
Closed #2.

**Comment by hemingkx** [comment]
config.json里面有一个"num_labels"参数，需要设置为标签数量～。

**Comment by zhw666888** [comment]
您好，这个原始文件没有这个参数，是需要自己手动设置？但是这样用您的github提供的数据，却没有报错。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hemingkx/CLUENER2020"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月9日(星期三) 晚上11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hemingkx/CLUENER2020] dataloder加载出错 (#2)





 
config.json里面有一个"num_labels"参数，需要设置为标签数量～。

**Comment by hemingkx** [comment]
是在BERT-CRF/experiments/clue/config.json这个路径下，有这个参数

**Comment by zhw666888** [comment]
这个文件夹应该是训练后保存模型的吧？我在开始换新数据的时候就跑不动了



---原始邮件---
发件人: "Heming ***@***.***&gt;
发送时间: 2021年6月10日(周四) 上午8:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hemingkx/CLUENER2020] dataloder加载出错 (#2)




 
是在BERT-CRF/experiments/clue/config.json这个路径下，有这个参数

**Comment by tianke0711** [comment]
同理 新数据就不行啦。能否提供代码测试 没有标签的test文本呢。现在都是test数据有标签的

**Comment by GitHubwwZ** [comment]
> 这个文件夹应该是训练后保存模型的吧？我在开始换新数据的时候就跑不动了
> […](#)
> ---原始邮件--- 发件人: "Heming ***@***.***&gt; 发送时间: 2021年6月10日(周四) 上午8:40 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [hemingkx/CLUENER2020] dataloder加载出错 (#2) 是在BERT-CRF/experiments/clue/config.json这个路径下，有这个参数 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
想问一下你的问题解决了吗？我也是换新的数据运行会报错。
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
在config文件中添加“num_labels”，也是报上面这个错误。
