### ISSUE TITLE
f1 score在第一次运行过后一直为0

### ISSUE THREAD

**Issue by bixingjian** [hemingkx/CLUENER2020#4]
你好我使用bert-base 运行bert-lstm-crf
在第一次运行的时候得出的结果很正常 
但之后的运行每次f1的结果都是0 请问是什么问题呢

**Comment by bixingjian** [comment]
另外还有一个特别有意思的现象, 我把num_epoch设置为5, f1就一直是0. 设置回到50轮后, f1有正常了, 请问能解答一下嘛.

**Comment by hemingkx** [comment]
这一点我没有遇到过，可以具体查看结果输出，如果发现问题的话我们可以讨论:)
