### ISSUE TITLE
运行出错，关于BertConfig

### ISSUE THREAD

**Issue by chenslcool** [hemingkx/CLUENER2020#9]
按照readme中的python、torch版本都配置了
但是运行出错：loading weights file pretrained_bert_models/chinese_roberta_wwm_large_ext/pytorch_model.bin的时候
AttributeError: 'BertConfig' object has no attribute 'lstm_embedding_size'

**Comment by hemingkx** [comment]
可以看一下readme这一块~
[model parameters](https://github.com/hemingkx/CLUENER2020#1model-parameters)
在./experiments/clue/config.json中设置了Bert/Roberta模型的基本参数，而在./pretrained_bert_models下的两个预训练文件夹中，config.json除了设置Bert/Roberta的基本参数外，还设置了'X'模型（如LSTM）参数，可根据需要进行更改。

**Comment by chenslcool** [comment]
不好意思，我没有很理解，config文件中是存在"lstm_embedding_size": 1024的，具体应该如何修改呢？
麻烦了

**Comment by hemingkx** [comment]
现在还有问题吗？如果你用的预训练模型没有lstm部分把这部分参数删去或者去找对应的model config即可~

**Comment by chenslcool** [comment]
已经解决了，谢谢！

**Comment by ZZQ908268856** [comment]
请问怎么解决的？

**Comment by 1357810la** [comment]
> 按照readme中的python、torch版本都配置了 但是运行出错：loading weights file pretrained_bert_models/chinese_roberta_wwm_large_ext/pytorch_model.bin的时候 AttributeError: 'BertConfig' object has no attribute 'lstm_embedding_size'
你好，能问下怎么解决的吗

**Comment by stay-leave** [comment]
我的解决方法：直接在预训练模型的config.json中加上对应的参数和值，比如这个是768，然后还有加上lstm的dropout，我设的0.5
